name: my-t3-boilerplate-dev
services:
  postgres:
    container_name: my-t3-boilerplate-postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: my-t3-boilerplate
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
